# Generated by Django 5.2.4 on 2026-09-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconnection",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="registeredmodel",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
