# Generated by Django 5.2.4 on 2026-09-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_preferences"),
        ("model_registry", "0002_descriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconnection",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_connections", to="accounts.project"
            ),
        ),
        migrations.AddField(
            model_name="modelconnection",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("workspace", "This workspace only"),
                    ("admins", "Workspaces where I'm admin"),
                    ("public", "Every workspace (public)"),
                ],
                default="workspace",
                max_length=20,
            ),
        ),
    ]
