# Generated by Django 5.2.4 on 2026-10-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_registry", "0004_otlpcredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otlpcredential",
            name="auth_mode",
            field=models.CharField(
                choices=[
                    ("none", "None (open)"),
                    ("basic", "Basic Auth"),
                    ("bearer", "Bearer Token"),
                ],
                default="basic",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="otlpcredential",
            name="salt",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="otlpcredential",
            name="secret_hash",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
