# Generated by Django 5.2.4 on 2026-10-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_registry", "0005_alter_otlpcredential_auth_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otlpcredential",
            name="token_prefix",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
    ]
