# Generated by Django 5.2.4 on 2026-10-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_registry", "0006_otlpcredential_token_prefix"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtlpSpan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.CharField(db_index=True, max_length=250)),
                ("trace_id", models.CharField(db_index=True, max_length=64)),
                ("span_id", models.CharField(max_length=64)),
                ("name", models.CharField(default="span", max_length=500)),
                ("kind", models.CharField(default="CHAIN", max_length=50)),
                (
                    "parent_span_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("start_time", models.FloatField(blank=True, null=True)),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(default="OK", max_length=20)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_otlp_span",
                "ordering": ["target_id", "start_time", "span_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_id", "trace_id", "span_id"),
                        name="unique_span_per_target_trace",
                    )
                ],
            },
        ),
    ]
