# Generated by Django 5.2.4 on 2026-10-02 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_preferences"),
        ("model_registry", "0007_otlpspan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("authority", models.CharField(blank=True, default="", max_length=250)),
                (
                    "trust_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=100)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_bases",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_knowledge_base",
                "ordering": ["project__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("url", models.URLField()),
                ("auth_config", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_servers",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_mcp_server",
                "ordering": ["project__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="MCPTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, default="")),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_tools",
                        to="accounts.project",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="model_registry.mcpserver",
                    ),
                ),
            ],
            options={
                "db_table": "core_mcp_tool",
                "ordering": ["server__name", "external_name"],
            },
        ),
        migrations.CreateModel(
            name="RetrievalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "search_mode",
                    models.CharField(
                        choices=[
                            ("semantic", "Semantic"),
                            ("hybrid", "Hybrid (semantic + BM25)"),
                        ],
                        default="semantic",
                        max_length=20,
                    ),
                ),
                ("top_k", models.PositiveIntegerField(default=5)),
                ("rerank_enabled", models.BooleanField(default=False)),
                ("rerank_top_k", models.PositiveIntegerField(default=4)),
                ("relevance_threshold", models.FloatField(blank=True, null=True)),
                ("bm25_weight", models.FloatField(blank=True, null=True)),
                ("full_context", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrieval_profiles",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_retrieval_profile",
                "ordering": ["project__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("builtin", "OpenWebUI built-in"),
                            ("openapi", "OpenAPI"),
                            ("custom", "Custom OpenWebUI function"),
                            ("mcp", "MCP"),
                        ],
                        default="builtin",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("output_schema", models.JSONField(blank=True, default=dict)),
                ("read_only", models.BooleanField(default=True)),
                ("has_side_effects", models.BooleanField(default=False)),
                ("external_network", models.BooleanField(default=False)),
                ("handles_sensitive_data", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_tool",
                "ordering": ["project__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, default="")),
                ("system_prompt", models.TextField(blank=True, default="")),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agents",
                        to="model_registry.registeredmodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="accounts.project",
                    ),
                ),
                (
                    "knowledge_bases",
                    models.ManyToManyField(
                        blank=True,
                        related_name="agents",
                        to="model_registry.knowledgebase",
                    ),
                ),
                (
                    "mcp_tools",
                    models.ManyToManyField(
                        blank=True, related_name="agents", to="model_registry.mcptool"
                    ),
                ),
                (
                    "retrieval_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="model_registry.retrievalprofile",
                    ),
                ),
                (
                    "tools",
                    models.ManyToManyField(
                        blank=True, related_name="agents", to="model_registry.tool"
                    ),
                ),
            ],
            options={
                "db_table": "core_agent",
                "ordering": ["project__name", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="knowledgebase",
            constraint=models.UniqueConstraint(
                fields=("project", "name"),
                name="unique_knowledge_base_name_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpserver",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_mcp_server_name_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="mcptool",
            constraint=models.UniqueConstraint(
                fields=("server", "external_name"), name="unique_mcp_tool_per_server"
            ),
        ),
        migrations.AddConstraint(
            model_name="retrievalprofile",
            constraint=models.UniqueConstraint(
                fields=("project", "name"),
                name="unique_retrieval_profile_name_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="tool",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_tool_name_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_agent_name_per_project"
            ),
        ),
    ]
