# Generated by Django 5.2.4 on 2026-10-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_preferences"),
        ("model_registry", "0008_agent_domain"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="knowledgebase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("project", "external_id"),
                name="unique_knowledge_base_external_id_per_project",
            ),
        ),
    ]
