# Generated by Django 5.2.4 on 2026-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_registry", "0009_add_kb_external_id_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="mcp_tools",
        ),
        migrations.DeleteModel(
            name="MCPTool",
        ),
        migrations.DeleteModel(
            name="MCPServer",
        ),
        migrations.AlterField(
            model_name="tool",
            name="type",
            field=models.CharField(
                choices=[
                    ("builtin", "OpenWebUI built-in"),
                    ("openapi", "OpenAPI"),
                    ("custom", "Custom OpenWebUI function"),
                ],
                default="builtin",
                max_length=20,
            ),
        ),
    ]
