# Generated by Django 5.2.4 on 2026-10-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "model_registry",
            "0011_knowledgebase_created_by_registeredmodel_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
