# Generated by Django 5.2.4 on 2026-10-05 10:16

from django.db import migrations, models

import model_registry.models


def copy_retrieval_profiles(apps, schema_editor):
    Agent = apps.get_model("model_registry", "Agent")
    RetrievalProfile = apps.get_model("model_registry", "RetrievalProfile")
    defaults = {
        "search_mode": "semantic",
        "top_k": 5,
        "rerank_enabled": False,
        "rerank_top_k": 4,
        "relevance_threshold": None,
        "bm25_weight": None,
        "full_context": False,
    }
    profiles = RetrievalProfile.objects.in_bulk()
    for agent in Agent.objects.all().iterator():
        settings = dict(defaults)
        profile = profiles.get(agent.retrieval_profile_id)
        if profile:
            settings.update({
                "search_mode": profile.search_mode,
                "top_k": profile.top_k,
                "rerank_enabled": profile.rerank_enabled,
                "rerank_top_k": profile.rerank_top_k,
                "relevance_threshold": profile.relevance_threshold,
                "bm25_weight": profile.bm25_weight,
                "full_context": profile.full_context,
            })
        Agent.objects.filter(pk=agent.pk).update(retrieval_settings=settings)


class Migration(migrations.Migration):
    dependencies = [
        ("model_registry", "0012_agent_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="retrieval_settings",
            field=models.JSONField(
                blank=True, default=model_registry.models.default_retrieval_settings
            ),
        ),
        migrations.RunPython(copy_retrieval_profiles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="agent",
            name="retrieval_profile",
        ),
        migrations.DeleteModel(
            name="RetrievalProfile",
        ),
    ]
