# Generated by Django 5.2.4 on 2026-10-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_registry", "0013_remove_agent_retrieval_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="type",
            field=models.CharField(
                choices=[
                    ("builtin", "Built-in"),
                    ("openapi", "OpenAPI"),
                    ("custom", "Custom function"),
                ],
                default="builtin",
                max_length=20,
            ),
        ),
    ]
