# Generated by Django 5.2.4 on 2026-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariorevision",
            name="documents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="scenariorevision",
            name="file_uri",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenariorevision",
            name="severity_ceiling",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
