"""Generate a standalone SimpleAudit script from a frozen AuditRun.

The generated script reproduces one run outside the platform using only the
``simpleaudit`` library: the exact scenarios (frozen revisions), the three
models (target / auditor / judge) as they were when the run was created, the
judge spec, and the generation settings. It is deterministic — the same run
always yields the same script — so it can be committed next to results for
reproducibility.

Secrets are never inlined. Each model's API key is read at run time from the
environment variable named by its connection's ``secret_reference``; when a
connection stores the key directly instead, the script prints a reminder to
export that variable before running.
"""

from __future__ import annotations

import json

from audits.models import AuditRun
from scenarios.models import ScenarioSetVersionItem


def _py(value) -> str:
    """A Python literal for use inside the generated script."""
    return json.dumps(value, indent=4, ensure_ascii=False)


def _endpoint_block(role: str, snap: dict, *, role_suffix: str = "") -> list[str]:
    """Constructor kwargs for one endpoint from its frozen snapshot."""
    provider = (snap.get("provider") or "").strip().lower()
    base_url = snap.get("base_url") or None
    # Mirror infra.engine._normalize_provider: an unrecognised label with a
    # base URL is an OpenAI-compatible endpoint.
    known = {"openai", "anthropic", "grok", "ollama", "vllm"}
    if provider not in known:
        provider = "openai" if base_url else (provider or "openai")
    lines = [f'{role}_model="{snap.get("model_id")}"', f'{role}_provider="{provider}"']
    if base_url:
        lines.append(f'{role}_base_url="{base_url}"')
    ref = (snap.get("secret_reference") or "").strip()
    if ref:
        lines.append(f'{role}_api_key=os.environ["{ref}"]')
    return lines


def _scenario_dicts(run: AuditRun) -> list[dict]:
    """The frozen scenario content of the run, in set order."""
    items = (
        ScenarioSetVersionItem.objects.filter(version=run.scenario_set_version)
        .select_related("scenario", "revision")
        .order_by("position")
    )
    out = []
    for item in items:
        d = {
            "name": item.scenario.key,
            "description": item.revision.description,
        }
        if item.revision.test_prompt:
            d["test_prompt"] = item.revision.test_prompt
        if item.revision.expected_behavior:
            d["expected_behavior"] = item.revision.expected_behavior
        out.append(d)
    return out


def generate_run_script(run: AuditRun) -> str:
    """Build the standalone script that re-runs ``run`` with plain simpleaudit."""
    gen = run.generation_parameters_snapshot or {}
    judge_snap = run.judge_config_snapshot or {}
    grading = judge_snap.get("judge") or {}
    spec = grading.get("spec") or {}

    target = run.target_config_snapshot or {}
    auditor = run.auditor_config_snapshot or {}

    n_reps = int(gen.get("n_repetitions") or 1)
    max_turns = int(gen.get("max_turns") or 5)
    language = gen.get("language") or "English"
    system_prompt = gen.get("system_prompt") or None

    header = (
        '"""Re-run of Studio run #%d "%s".\n'
        "\n"
        "Generated by SimpleAudit Studio — edit freely.\n"
        "Requires: pip install simpleaudit\n"
        "Set the API-key environment variables noted below, then:\n"
        "    python this_file.py\n"
        '"""\n'
    ) % (run.id, run.name)

    imports = ["import os"]
    body_parts: list[str] = []

    # --- Scenarios ---------------------------------------------------------
    scenarios = _scenario_dicts(run)
    set_name = run.scenario_set_version.scenario_set.name
    set_version = run.scenario_set_version.version
    body_parts.append(
        f"# Scenarios: \"{set_name}\" v{set_version} ({len(scenarios)} scenarios, frozen)\n"
        f"scenarios = {_py(scenarios)}"
    )

    # --- Judge -------------------------------------------------------------
    judge_lines = []
    base = spec.get("base") or ""
    criteria = spec.get("criteria") or ""
    probe_prompt = spec.get("probe_prompt") or None
    if base and not criteria:
        # An unedited SimpleAudit judge: pass by name (None = unnamed default).
        if base != "default":
            judge_lines.append(f'judge="{base}"')
    elif base:
        # Edited criteria on top of a library judge.
        judge_lines.append(
            "judge=customize_judge(\n"
            f"    {json.dumps(base)},\n"
            f"    criteria={_py(criteria)},\n"
            ")"
        )
        imports.append("from simpleaudit.judges import customize_judge")
    else:
        options = spec.get("options") or {}
        judge_lines.append(
            "judge=build_judge(\n"
            f"    {json.dumps(spec.get('output'))},\n"
            f"    criteria={_py(criteria)},\n"
            f"    dimensions={_py(options.get('dimensions') or ())},\n"
            f"    question={_py(options.get('question'))},\n"
            f"    pass_when={_py(options.get('pass_when', True))},\n"
            ")"
        )
        imports.append("from simpleaudit.judges import build_judge")
    if probe_prompt:
        judge_lines.append(f"probe_prompt={_py(probe_prompt)}")

    # --- Endpoint blocks ----------------------------------------------------
    target_lines = _endpoint_block("target", target)
    auditor_lines = _endpoint_block("auditor", auditor)
    judge_endpoint_lines = _endpoint_block("judge", judge_snap)

    ctor = target_lines + auditor_lines + judge_endpoint_lines + judge_lines
    if system_prompt:
        ctor.append(f"system_prompt={_py(system_prompt)}")
    if max_turns != 5:
        ctor.append(f"max_turns={max_turns}")
    ctor.append(f"show_progress=True")

    # --- Run ----------------------------------------------------------------
    if n_reps > 1:
        # AuditExperiment takes the target as a models list; auditor and judge
        # stay constructor kwargs.
        model_entry = "{\n" + ",\n".join(f"    {line}" for line in target_lines) + ",\n}"
        ctor = [f"models=[{model_entry}]"]
        ctor += [line for line in (auditor_lines + judge_endpoint_lines + judge_lines)]
        if system_prompt:
            ctor.append(f"system_prompt={_py(system_prompt)}")
        if max_turns != 5:
            ctor.append(f"max_turns={max_turns}")
        ctor.append(f"n_repetitions={n_reps}")
        ctor.append("show_progress=True")
        imports[-1] = "from simpleaudit import AuditExperiment"
        var_name, cls = "experiment", "AuditExperiment"
        run_call = f"results = experiment.run(scenarios, language={_py(language)})"
    else:
        imports[-1] = "from simpleaudit import ModelAuditor"
        var_name, cls = "auditor", "ModelAuditor"
        run_call = f"results = auditor.run(scenarios, language={_py(language)})"

    ctor_text = "".join(f"    {line},\n" for line in ctor)
    body_parts.append(f"{var_name} = {cls}(\n{ctor_text})")

    body_parts.append(
        f"{run_call}\n"
        "results.summary()\n"
        'results.save("results.json")'
    )

    # --- Secret reminders ----------------------------------------------------
    notes = []
    for role, snap in (("target", target), ("auditor", auditor), ("judge", judge_snap)):
        ref = (snap.get("secret_reference") or "").strip()
        if not ref:
            notes.append(
                f"# NOTE: the {role} connection stored its API key directly in Studio;\n"
                f"# export it as {role.upper()}_API_KEY (or edit the api_key kwarg above) before running."
            )
    if notes:
        body_parts.insert(0, "\n".join(notes))

    script = header + "\n".join(dict.fromkeys(imports)) + "\n\n\n" + "\n\n\n".join(body_parts) + "\n"
    return script
