# Generated by Django 5.2.4 on 2026-09-28 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_user_preferences"),
        ("model_registry", "0002_descriptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judges",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JudgeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("rubric", models.CharField(blank=True, default="", max_length=64)),
                ("probe_prompt", models.TextField(blank=True, default="")),
                ("judge_prompt", models.TextField(blank=True, default="")),
                ("note", models.CharField(blank=True, default="", max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="judges.judge",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="judge_versions",
                        to="model_registry.registeredmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["judge_id", "-version"],
            },
        ),
        migrations.AddConstraint(
            model_name="judge",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_judge_name_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="judgeversion",
            constraint=models.UniqueConstraint(
                fields=("judge", "version"), name="unique_judge_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="judgeversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="judge_version_positive"
            ),
        ),
    ]
