# Generated by Django 5.2.4 on 2026-09-28 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("judges", "0001_judges"),
        # Monitors copy their judge model from judge versions first.
        ("audits", "0004_judge_model_per_run"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgeversion",
            name="model",
        ),
    ]
