# Generated by Django 5.2.4 on 2026-10-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_project_created_by_projectmembership_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="openwebui_admin_group_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="openwebui_group_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="openwebui_user_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
