# Generated by Django 5.2.4 on 2026-09-27 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("model_registry", "0001_initial"),
        ("scenarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.PositiveBigIntegerField(db_index=True)),
                ("version_item_id", models.CharField(db_index=True, max_length=64)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_audit_event",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["run_id", "id"], name="audit_event_run_id_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("factors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiments",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_experiment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("preparing", "Preparing"),
                            ("target_execution", "Target execution"),
                            ("auditing", "Auditing"),
                            ("judging", "Judging"),
                            ("aggregation", "Aggregation"),
                            ("report_generation", "Report generation"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("target_config_snapshot", models.JSONField()),
                ("auditor_config_snapshot", models.JSONField()),
                ("judge_config_snapshot", models.JSONField()),
                ("generation_parameters_snapshot", models.JSONField()),
                ("simpleaudit_version", models.CharField(max_length=120)),
                ("git_commit", models.CharField(max_length=120)),
                ("runtime_metadata", models.JSONField(blank=True, default=dict)),
                ("workflow_run_id", models.CharField(blank=True, max_length=250)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_scenarios", models.PositiveIntegerField(default=0)),
                ("completed_scenarios", models.PositiveIntegerField(default=0)),
                ("successful_scenarios", models.PositiveIntegerField(default=0)),
                ("failed_scenarios", models.PositiveIntegerField(default=0)),
                ("retried_scenarios", models.PositiveIntegerField(default=0)),
                ("summary_metrics", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("error_message", models.TextField(blank=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auditor_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="auditor_audit_runs",
                        to="model_registry.registeredmodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "judge_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="judge_audit_runs",
                        to="model_registry.registeredmodel",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_runs",
                        to="accounts.project",
                    ),
                ),
                (
                    "scenario_set_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="audit_runs",
                        to="scenarios.scenariosetversion",
                    ),
                ),
                (
                    "target_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="target_audit_runs",
                        to="model_registry.registeredmodel",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="audits.experiment",
                    ),
                ),
            ],
            options={
                "db_table": "core_audit_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("enabled", models.BooleanField(default=True)),
                ("generation_parameters", models.JSONField(blank=True, default=dict)),
                ("interval_hours", models.PositiveIntegerField(default=168)),
                ("cron_expression", models.CharField(blank=True, max_length=120)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("next_run_at", models.DateTimeField(db_index=True)),
                ("last_tick_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auditor_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="auditor_monitors",
                        to="model_registry.registeredmodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitors",
                        to="audits.experiment",
                    ),
                ),
                (
                    "judge_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="judge_monitors",
                        to="model_registry.registeredmodel",
                    ),
                ),
                (
                    "last_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="audits.auditrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="accounts.project",
                    ),
                ),
                (
                    "scenario_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="scenarios.scenarioset",
                    ),
                ),
                (
                    "scenario_set_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="monitors",
                        to="scenarios.scenariosetversion",
                    ),
                ),
                (
                    "target_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="target_monitors",
                        to="model_registry.registeredmodel",
                    ),
                ),
            ],
            options={
                "db_table": "core_monitor",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="auditrun",
            name="monitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="audits.monitor",
            ),
        ),
        migrations.CreateModel(
            name="ScenarioResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.PositiveBigIntegerField()),
                ("version_item_id", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_scenario_result",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "version_item_id"),
                        name="unique_scenario_result_per_run_item",
                    )
                ],
            },
        ),
    ]
