# Generated by Django 5.2.4 on 2026-10-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0004_judge_model_per_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditrun",
            name="trace_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
