# Generated by Django 5.2.4 on 2026-09-27 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_project_archived"),
        ("audits", "0004_swap_endpoint_fks_for_models"),
        ("model_registry", "0003_remove_modeleendpoint"),
        ("scenarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("enabled", models.BooleanField(default=True)),
                ("generation_parameters", models.JSONField(blank=True, default=dict)),
                ("interval_hours", models.PositiveIntegerField(default=168)),
                ("next_run_at", models.DateTimeField(db_index=True)),
                ("last_tick_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auditor_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="auditor_audit_schedules",
                        to="model_registry.registeredmodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "judge_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="judge_audit_schedules",
                        to="model_registry.registeredmodel",
                    ),
                ),
                (
                    "last_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="audits.auditrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_schedules",
                        to="accounts.project",
                    ),
                ),
                (
                    "scenario_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_schedules",
                        to="scenarios.scenarioset",
                    ),
                ),
                (
                    "scenario_set_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="audit_schedules",
                        to="scenarios.scenariosetversion",
                    ),
                ),
                (
                    "target_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="target_audit_schedules",
                        to="model_registry.registeredmodel",
                    ),
                ),
            ],
            options={
                "db_table": "core_audit_schedule",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="auditrun",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="audits.auditschedule",
            ),
        ),
    ]
