# Generated by Django 5.2.4 on 2026-09-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0005_audit_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditschedule",
            name="cron_expression",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
