# Generated by Django 5.2.4 on 2026-10-02 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_auditrun_trace_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='next_run_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
