# Generated by Django 5.2.4 on 2026-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0006_schedule_cron_expression"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditschedule",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
    ]
