# Generated by Django 5.2.4 on 2026-10-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0006_alter_monitor_next_run_at"),
        ("model_registry", "0008_agent_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditrun",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_runs",
                to="model_registry.agent",
            ),
        ),
        migrations.AddField(
            model_name="auditrun",
            name="agent_config_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
